# Use Netlify Function as the Clerk proxy
[[redirects]]
  from = "/clerk/*"
  to = "/.netlify/functions/clerk-proxy/:splat"
  status = 200
  force = true

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "PUBLIC_CLERK_PUBLISHABLE_KEY"
  # Ensure your Node runtime is 18+ to use native fetch
  NODE_VERSION = "18"
